#define TCR_CONFIG_REGION_48bit (((64 - 48) << 0) | ((64 - 48) << 16))
#define TCR_CONFIG_4KB ((0b00 << 14) |  (0b10 << 30))
#define TCR_CONFIG_DEFAULT (TCR_CONFIG_REGION_48bit | TCR_CONFIG_4KB)

#define MAIR_DEVICE_nGnRnE 0b00000000
#define MAIR_NORMAL_NOCACHE 0b01000100
#define MAIR_IDX_DEVICE_nGnRnE 0
#define MAIR_IDX_NORMAL_NOCACHE 1

#define PD_TABLE 0b11
#define PD_BLOCK 0b01
#define PD_ACCESS (1 << 10)
#define BOOT_PGD_ATTR PD_TABLE
#define BOOT_PUD0_ATTR PD_TABLE
#define BOOT_PUD1_ATTR (PD_ACCESS | (MAIR_IDX_DEVICE_nGnRnE << 2) | PD_BLOCK)
#define BOOT_PMD0_ATTR_MMIO (PD_ACCESS | (MAIR_IDX_DEVICE_nGnRnE << 2) | PD_BLOCK)
#define BOOT_PMD0_ATTR_RAM (PD_ACCESS | (MAIR_IDX_NORMAL_NOCACHE << 2) | PD_BLOCK)

#define RO_BIT (1 << 7)
#define RW_BIT (0 << 7)
#define USR_EXE_NEVER_BIT (1 << 54)
#define KERNEL_EXE_NEVER_BIT (1 << 53)   //if set RW_BIT and USER_KERNEL_BIT, then KERNEL_EXE_BIT will be ineffective
#define ONLY_KERNEL_BIT (0 << 6)
#define USER_KERNEL_BIT (1 << 6)
#define PGD_ATTR PD_TABLE
#define PUD_ATTR PD_TABLE
#define PMD_ATTR PD_TABLE
#define PTE_ATTR_CODE (PD_ACCESS | USER_KERNEL_BIT | RO_BIT | (MAIR_IDX_NORMAL_NOCACHE << 2) | PD_TABLE)
#define PTE_ATTR_STACK (PD_ACCESS | USER_KERNEL_BIT | RW_BIT | (MAIR_IDX_NORMAL_NOCACHE << 2) | PD_TABLE)
#define PTE_ATTR_BASE (USER_KERNEL_BIT | (MAIR_IDX_NORMAL_NOCACHE << 2) | PD_TABLE)

#define PROT_NONE  (0)
#define PROT_READ  (1 << 0)
#define PROT_WRITE (1 << 1)
#define PROT_EXEC  (1 << 2)